name: robotkernel
channels:
  - conda-forge
dependencies:
  - python >=3.6,<3.8.0a0
  - jupyterlab >=1.2.4,<1.3
  - nodejs >=11,<12
  - pip
  - pip:
    - pillow==6.2.1
    - robotkernel==1.3.0
    - robotframework==3.1.2
    - selenium==3.141.0
    - robotframework-seleniumlibrary==4.1.0
